Squashed all previous commits into this single one
Current state: Compiles without warnings (shell module commented out),
most stuff seems to work, only known error is ipv6 being broken (?).

Signed-off-by: Uli Schlachter <psychon@znc.in>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2579,6 +2579,12 @@ case "${host_os}" in
 	;;
 	cygwin)
 		ISCYGWIN=1
+		ISWIN=1
+	;;
+	mingw*)
+		ISMINGW=1
+		ISWIN=1
+		appendLib -lws2_32
 	;;
 	darwin*)
 		ISDARWIN=1
@@ -2642,6 +2648,11 @@ if test "$DEBUG" != "no"; then
 else
 	if test "x$OPTIMIZE" = "xyes"; then
 		appendCXX -O2
+	fi
+	if test -n "$ISMINGW" ; then
+		{ { echo "$as_me:$LINENO: error: You have to use --enable-debug for mingw" >&5
+echo "$as_me: error: You have to use --enable-debug for mingw" >&2;}
+   { (exit 1); exit 1; }; }
 	fi
 fi
 
@@ -3183,6 +3194,11 @@ fi
 
 	appendLib "$SAVED_LIBS"
 
+	if test -n "$ISMINGW" ; then
+		# Just pretend, Modules.cpp will handle this
+		FOUND_DL=yes
+	fi
+
 	if test $FOUND_DL = "no" ; then
 		{ { $as_echo "$as_me:$LINENO: error: could not find dlopen. Try --disable-modules" >&5
 $as_echo "$as_me: error: could not find dlopen. Try --disable-modules" >&2;}
@@ -3203,14 +3219,21 @@ $as_echo "$as_me: error: could not find dlopen. Try --disable-modules" >&2;}
 		appendMod -mimpure-text
 	fi
 
-	if test -z "$ISCYGWIN" ; then
-		# cygwin doesn't need -fPIC, everything else does (for modules)
+	if test -z "$ISWIN" ; then
+		# windows doesn't need -fPIC, everything else does (for modules)
 		# warning: -fPIC ignored for target (all code is position independent)
 		appendMod -fPIC
 	else
 		# But cygwin does want most of znc in a shared lib
 		LIBZNC="libznc.dll"
 		LIBZNCDIR="$libdir/znc"
+	fi
+
+	if test -n "$ISMINGW" ; then
+		# To get rid of some warnings, mingw needs this flag when
+		# linking to libznc.dll
+		appendMod -Wl,--enable-auto-import
+		appendLD -Wl,--enable-auto-import
 	fi
 
 	if test -z "$ISDARWIN"; then
